import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Glider from "../components/glide/Glider";
import Products from "../components/products/Products";
import { useFunctions } from "../context/FunctionsContext";
import LoadingSpinner from "../components/loadingSpinner/LoadingSpinner";

export default function Home() {
  const { error, loadingSpinner } = useFunctions();
  return (
    <div className={styles.container}>
      <Head>
        <title>Easy Play</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<main className={styles.main}>
      {error && (
        <span style={{ display:"flex",justifyContent:"center", fontSize: "90px",color:"red"}}>Server error</span>
      )}

      
      
      {loadingSpinner ? <LoadingSpinner /> : <div><Glider/>  <Products /></div>}

      </main>

      <footer className={styles.footer}
       style={{flex:"1 1 auto"}}
       >
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
